// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package server

import (
	"encoding/json"
	"fmt"

	"github.com/gin-gonic/gin"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for HealthResponseStatus.
const (
	Degraded  HealthResponseStatus = "degraded"
	Healthy   HealthResponseStatus = "healthy"
	Unhealthy HealthResponseStatus = "unhealthy"
)

// Defines values for ResponseCode.
const (
	CHECKFAILED       ResponseCode = "CHECK_FAILED"
	OK                ResponseCode = "OK"
	RATELIMITEXCEEDED ResponseCode = "RATE_LIMIT_EXCEEDED"
)

// AccessHookRequest Access-hook request from engine to hook server
type AccessHookRequest struct {
	// Toolkits Map of a group of tools
	Toolkits Toolkits `json:"toolkits"`

	// UserId User ID
	UserId string `json:"user_id"`
}

// AccessHookResult Access-hook response from hook server to engine. If 'only' is included, ONLY those are allowed (deny list ignored).
type AccessHookResult struct {
	// Deny Map of a group of tools
	Deny *Toolkits `json:"deny,omitempty"`

	// Only Map of a group of tools
	Only *Toolkits `json:"only,omitempty"`
}

// Authorization Authorization information
type Authorization struct {
	// Oauth2 OAuth2 authorization details
	Oauth2 *OAuth2Details `json:"oauth2,omitempty"`

	// ProviderId ID of the OAuth provider
	ProviderId *string `json:"provider_id,omitempty"`
}

// ContentBlock A block in Arcade's protocol-neutral content-block format: `text`, `image`, `audio`, `resource_link`, or `resource`, with `annotations` and `_meta`. The format follows the MCP content-block model, so MCP tooling and documentation apply, and `type` selects the block's other fields as MCP defines them: https://modelcontextprotocol.io/specification/2026-07-28/server/tools#tool-result. Content a server returns in another protocol would be converted into this format.
type ContentBlock struct {
	// Type The block type, e.g. "text", "image", "audio", "resource_link", or "resource"
	Type                 string                 `json:"type"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ErrorResponse Error response from webhook server
type ErrorResponse struct {
	// Code Response code from hook server
	Code *ResponseCode `json:"code,omitempty"`

	// Error Human-readable error message
	Error *string `json:"error,omitempty"`
}

// HealthResponse Health check response
type HealthResponse struct {
	// Status Health status
	Status *HealthResponseStatus `json:"status,omitempty"`
}

// HealthResponseStatus Health status
type HealthResponseStatus string

// OAuth2Details OAuth2 authorization details
type OAuth2Details struct {
	// At Access token claims (only present when token is a JWT; absent for opaque tokens)
	At *map[string]interface{} `json:"at,omitempty"`

	// Scopes OAuth scopes (always available from token response)
	Scopes *[]string `json:"scopes,omitempty"`

	// UserInfo User information from oauth2 provider
	UserInfo *map[string]interface{} `json:"user_info,omitempty"`
}

// PostHookOverride Override response parameters
type PostHookOverride struct {
	// Content Replace the content blocks, in the same format as the request's `content`. Omit to forward the request's `content` unchanged. An empty list removes every block, and clients then receive `output` rendered as a single text block. A hook that rewrites `output` should rewrite `content` too, or the server's own text reaches the client as it was sent.
	Content *[]ContentBlock `json:"content,omitempty"`

	// Output Override the output value (any JSON type — string, number, object, array, etc.)
	Output interface{} `json:"output,omitempty"`
}

// PostHookRequest Post-hook request from engine to hook server
type PostHookRequest struct {
	// Content The content blocks the tool's server returned alongside its structured result, in Arcade's protocol-neutral content-block format (see `ContentBlock`). Today the only source is remote MCP servers. Fields the block definitions include are forwarded, annotations and `_meta` included, except that a `resource_link` block may arrive without its `title`, `size`, `icons`, or `_meta`. Fields outside the block definitions may be dropped. Clients receive the text blocks as the unstructured side of the result. Absent when the server sent no content of its own, in which case clients receive `output` rendered as text. Also absent on error results, whose error text arrives in `execution_error`.
	Content *[]ContentBlock `json:"content,omitempty"`

	// Context Tool execution context
	Context ToolContext `json:"context"`

	// ExecutionCode Status code from the server
	ExecutionCode *string `json:"execution_code,omitempty"`

	// ExecutionError Execution error from the tool call
	ExecutionError *string `json:"execution_error,omitempty"`

	// ExecutionId Allows tracking requests and responses
	ExecutionId string `json:"execution_id"`

	// Inputs Tool inputs (name -> value)
	Inputs *map[string]interface{} `json:"inputs,omitempty"`

	// Output The tool's output value (any JSON type — string, number, object, array, etc.)
	Output interface{} `json:"output,omitempty"`

	// Success Whether the tool succeeded
	Success *bool `json:"success,omitempty"`

	// Tool Tool identification information
	Tool ToolInfo `json:"tool"`
}

// PostHookResult Post-hook response from hook server to engine
type PostHookResult struct {
	// Code Response code from hook server
	Code ResponseCode `json:"code"`

	// ErrorMessage Error message for the Agent
	ErrorMessage *string `json:"error_message,omitempty"`

	// Override Override response parameters
	Override *PostHookOverride `json:"override,omitempty"`
}

// PreHookOverride Override execution parameters
type PreHookOverride struct {
	// Inputs Override tool inputs
	Inputs *map[string]interface{} `json:"inputs,omitempty"`

	// Secrets Override secrets
	Secrets *[]map[string]string `json:"secrets,omitempty"`
}

// PreHookRequest Pre-hook request from engine to hook server
type PreHookRequest struct {
	// Context Tool execution context
	Context ToolContext `json:"context"`

	// ExecutionId Allows tracking requests and responses
	ExecutionId string `json:"execution_id"`

	// Inputs Tool inputs (name -> value)
	Inputs map[string]interface{} `json:"inputs"`

	// Tool Tool identification information
	Tool ToolInfo `json:"tool"`
}

// PreHookResult Pre-hook response from hook server to engine
type PreHookResult struct {
	// Code Response code from hook server
	Code ResponseCode `json:"code"`

	// ErrorMessage Error message for the Agent
	ErrorMessage *string `json:"error_message,omitempty"`

	// Override Override execution parameters
	Override *PreHookOverride `json:"override,omitempty"`
}

// ResponseCode Response code from hook server
type ResponseCode string

// SecretRequirement Required secret definition
type SecretRequirement struct {
	// Name Secret name
	Name string `json:"name"`
}

// ToolAuthRequirements Authorization requirements for a tool
type ToolAuthRequirements struct {
	Oauth2 *struct {
		// Scopes Required scopes
		Scopes *[]string `json:"scopes,omitempty"`
	} `json:"oauth2,omitempty"`

	// ProviderId Provider ID
	ProviderId *string `json:"provider_id,omitempty"`

	// ProviderType Provider type
	ProviderType *string `json:"provider_type,omitempty"`
}

// ToolBehavior Behavior metadata for a tool
type ToolBehavior struct {
	// Destructive Whether the tool can delete or irreversibly modify data
	Destructive *bool `json:"destructive,omitempty"`

	// Idempotent Whether repeated calls with the same inputs produce the same result
	Idempotent *bool `json:"idempotent,omitempty"`

	// OpenWorld Whether the tool can affect state outside its defined outputs
	OpenWorld *bool `json:"open_world,omitempty"`

	// Operations Operations this tool performs (e.g., "read", "create", "update", "delete", "opaque"). Sourced from the tool's Behavior.Operations metadata. See https://docs.arcade.dev/en/guides/create-tools/tool-basics/add-tool-metadata for valid values.
	Operations *[]string `json:"operations,omitempty"`

	// ReadOnly Whether the tool only reads data
	ReadOnly *bool `json:"read_only,omitempty"`
}

// ToolClassification Classification metadata for a tool
type ToolClassification struct {
	// ServiceDomains Service domains this tool interfaces with (e.g., "crm", "email", "calendar"). Sourced from the tool's Classification.ServiceDomains metadata. See https://docs.arcade.dev/en/guides/create-tools/tool-basics/add-tool-metadata for valid values.
	ServiceDomains *[]string `json:"service_domains,omitempty"`
}

// ToolContext Tool execution context
type ToolContext struct {
	Authorization *[]Authorization `json:"authorization,omitempty"`

	// Metadata Arbitrary metadata from tool
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// Secrets Required secrets (key only, no values)
	Secrets *[]string `json:"secrets,omitempty"`

	// UserId User ID for access checks
	UserId *string `json:"user_id,omitempty"`
}

// ToolInfo Tool identification information
type ToolInfo struct {
	// Metadata Tool metadata
	Metadata *ToolVersionInfoMetadata `json:"metadata,omitempty"`

	// Name Tool name
	Name string `json:"name"`

	// Toolkit Toolkit name
	Toolkit string `json:"toolkit"`

	// Version Tool version
	Version string `json:"version"`
}

// ToolVersionInfo Version-specific information for a tool
type ToolVersionInfo struct {
	// Metadata Tool metadata
	Metadata *ToolVersionInfoMetadata `json:"metadata,omitempty"`

	// Requirements Requirements for a toolkit (group of tools)
	Requirements *ToolkitRequirements `json:"requirements,omitempty"`

	// Version Tool version
	Version *string `json:"version,omitempty"`
}

// ToolVersionInfoMetadata Tool metadata
type ToolVersionInfoMetadata struct {
	// Behavior Behavior metadata for a tool
	Behavior *ToolBehavior `json:"behavior,omitempty"`

	// Classification Classification metadata for a tool
	Classification *ToolClassification `json:"classification,omitempty"`

	// Extras Arbitrary additional metadata (e.g., {"IdP": "entra_id"})
	Extras *map[string]interface{} `json:"extras,omitempty"`
}

// ToolkitInfo Information about a group of tools
type ToolkitInfo struct {
	// Tools Map of tool name to array of tool version info (there may be multiple versions of tools)
	Tools *map[string][]ToolVersionInfo `json:"tools,omitempty"`
}

// ToolkitRequirements Requirements for a toolkit (group of tools)
type ToolkitRequirements struct {
	// Authorization Authorization requirements for a tool
	Authorization *[]ToolAuthRequirements `json:"authorization,omitempty"`

	// Secrets Required secrets
	Secrets *[]SecretRequirement `json:"secrets,omitempty"`
}

// Toolkits Map of a group of tools
type Toolkits map[string]ToolkitInfo

// AccessHookJSONRequestBody defines body for AccessHook for application/json ContentType.
type AccessHookJSONRequestBody = AccessHookRequest

// PostHookJSONRequestBody defines body for PostHook for application/json ContentType.
type PostHookJSONRequestBody = PostHookRequest

// PreHookJSONRequestBody defines body for PreHook for application/json ContentType.
type PreHookJSONRequestBody = PreHookRequest

// Getter for additional properties for ContentBlock. Returns the specified
// element and whether it was found
func (a ContentBlock) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ContentBlock
func (a *ContentBlock) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ContentBlock to handle AdditionalProperties
func (a *ContentBlock) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ContentBlock to handle AdditionalProperties
func (a ContentBlock) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Access control hook
	// (POST /access)
	AccessHook(c *gin.Context)
	// Health check endpoint
	// (GET /health)
	HealthCheck(c *gin.Context)
	// Post-execution hook
	// (POST /post)
	PostHook(c *gin.Context)
	// Pre-execution hook
	// (POST /pre)
	PreHook(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// AccessHook operation middleware
func (siw *ServerInterfaceWrapper) AccessHook(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AccessHook(c)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.HealthCheck(c)
}

// PostHook operation middleware
func (siw *ServerInterfaceWrapper) PostHook(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostHook(c)
}

// PreHook operation middleware
func (siw *ServerInterfaceWrapper) PreHook(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PreHook(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/access", wrapper.AccessHook)
	router.GET(options.BaseURL+"/health", wrapper.HealthCheck)
	router.POST(options.BaseURL+"/post", wrapper.PostHook)
	router.POST(options.BaseURL+"/pre", wrapper.PreHook)
}
